# Generated by Django 2.0 on 2017-12-08 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descripton', models.TextField()),
                ('status', models.CharField(choices=[('Pedente', 'Pendente'), ('Em_andamento', 'Em_andamento'), ('Finzalizado', 'Finalizado')], default='Pendente', max_length=20)),
                ('user', models.ForeignKey(on_delete=False, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
