# Generated by Django 2.0 on 2017-12-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='descripton',
            new_name='description',
        ),
    ]
