# Generated by Django 2.0 on 2017-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20171208_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
